server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:changeit}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate         # En prod no generes esquema
    show-sql: false

logging:
  level:
    root: INFO
  file:
    name: logs/app.log           # (Opcional) si quieres volcar a fichero
